baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Paper Site'
theme = "paper"
paginate = 3
enableInlineShortcodes = true



disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # add disqus comments

[params]
  # color style
  color = 'linen'                 # linen, wheat, gray, light

  # header social icons
  twitter = 'YOUR_TWITTER_ID'     # twitter.com/YOUR_TWITTER_ID
  github = 'YOUR_GITHUB_ID'       # github.com/YOUR_GITHUB_ID
  instagram = 'YOUR_INSTAGRAM_ID' # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                      # show rss icon with link

  # home page profile
  avatar = 'GRAVATAR_EMAIL'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
  name = 'YOUR_NAME'
  bio = 'YOUR_BIO'

  # misc
  disableHLJS = true              # disable requesting highlight.js
  monoDarkIcon = true             # show monochrome dark mode icon


# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true